#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

bosh events --object-type=deployment --after="${previous_backup}" --json > bosh_events.json

# produce a changelog (metadata) by returning date+action+deployment for successfully completed events
metadata=$(jq '[.Tables[0].Rows[] | select(.id | contains(" <- ")) | select(.error == "" ) | {name: .time, value: ("Deployment `" + .deployment + "` " + .action + "ed")} ]' < bosh_events.json)

echo "{ \"version\" : { \"last_event\": \"${current_version}\", \"previous_backup\": \"${previous_backup}\" }, \"metadata\": ${metadata} }" >&3

exit 0
